
gennydb:
  image: mariadb
  environment:
    - MYSQL_DATABASE=gennydb
    - MYSQL_USER=genny
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password
    - ADMIN_USERNAME=admin
    - ADMIN_PASSWORD=password
  ports:
    - "3337:3306"
   


wildfly-qwanda-service:
  image: gennyproject/wildfly-qwanda-service:latest 
  links:
    - gennydb:gennydb
  environment:
    - MYSQL_PORT_3306_TCP_ADDR=gennydb
    - MYSQL_PORT_3306_TCP_PORT=3306
    - MYSQL_DATABASE=gennydb
    - MYSQL_USER=genny
    - MYSQL_PASSWORD=password
    - ADMIN_USERNAME=admin
    - ADMIN_PASSWORD=password
    - CORS_ALLOWED_ORIGINS="https://genny.outcome-hub.com,http://qwanda-service.outcome-hub.com,https://qwanda-service.outcome-hub.com,http://localhost:58080,http://localhost:3000,http://localhost:5000,http://localhost:8998"
    - HOSTIP=10.1.1.83
  ports:
    - "8998:8998"
    - "50293:50293"
    - "58080:8080"
    - "59990:9990"

   


